server.port=9001

eureka.client.service-url.defaultZone=http://localhost:9002/eureka/

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}

management.endpoints.web.exposure.include=*