spring.application.name=gateway
server.port=9001

management.endpoints.web.exposure.include=*

eureka.client.service-url.defaultZone=http://localhost:9002/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}

eureka.instance.health-check-url=http://localhost:${server.port}/actuator/health
eureka.instance.status-page-url=http://localhost:${server.port}/actuator/info
eureka.instance.home-page-url=http://localhost:${server.port}/

spring.cloud.gateway.server.webmvc.routes[0].id=app_route
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://APP
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/**
